### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by sweetro** [testdouble/static-rails#13]
Thanks for making this library!

I was wondering if anyone has successfully deployed a site to Heroku.

I've configured a gatsby site and locally, everything builds fine.

When deploying to heroku, I get a `undefined method 'with_unbundled_env' for Bundler:Module` error, which should not be the case since it's bundling with Bundler 2 which includes that method.

I tried patching the `CompilesSites` class to use `with_clean_env` (which  with_unbundled_env was introduced in favor of) and then I'm getting a failure from `system(site.env, site.compile_command)`.

Here's my config if it's helpful.

```
StaticRails.config do |config|
  config.proxy_requests = false
  config.serve_compiled_assets = true
  config.sites = [{
    name: "home",
    url_root_path: "/",
    source_dir: "static/home",
    start_server: false,
    url_skip_paths_starting_with: ["/api", "/sidekiq", "/cable"],
    compile_command: "npx gatsby build",
    compile_dir: "static/home/public"
  }]
end
```

Thanks!

**Comment by searls** [comment]
yes, we're hosting apps on Heroku with this gem. It sounds like a configuration error with your app that's resulting in heroku using an old bundler instead of bundler 2.

**Comment by sweetro** [comment]
Thank you for the follow up! That seems like it's it for Bundler - looks like it's defaulting to 2.0.2, despite `with_unbundled_env` not being introduced until `2.1.0`.

The other issue i'm hitting is that once it's in that block, the `npx gatsby` command isn't found - I believe that's because heroku by default runs build packages at the root, but since the static site is living in a `static/` subdirectory, when the `Dir.chdir(config.app.root.join(site.source_dir)) do` is called, the `system` call can't access `npx`. 

Did you need to configure any special subdirectory buildpacks (i.e. https://elements.heroku.com/buildpacks/pagedraw/heroku-buildpack-select-subdir) or any custom build scripts to get this working (based on https://github.com/testdouble/static-rails/blob/master/example/package.json it doesn't look like it?) 

Apologies since this is probably getting too deep into heroku config land, but figured I'd double check to see if there were any obvious steps I was missing that weren't outlined in the docs. Thanks!

**Comment by searls** [comment]
I'd encourage you to experiment. For node-based projects, I'd just have an npm script assigned in their package.json so that you can unambiguously invoke it with `npm run blah` without concern for which version `npx` might pull based on the cwd
